version: '3'
volumes:
  bundle:
  postgres:

services:
  db:
    image: postgres:12.1
    volumes:
      - /var/lib/postgresql/data
  web:
    build: .
    command: ./bin/start.sh
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres@db:5432
    tty: true
    stdin_open: true
