default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: course_enrollment_development

test:
  <<: *default
  database: course_enrollment_test

production:
  <<: *default
  database: course_enrollment_production
  username: course_enrollment
  password: <%= ENV['COURSE_ENROLLMENT_DATABASE_PASSWORD'] %>
